/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easy.delievery;

import java.awt.Window;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Server
 */
public class PrintRequestWindow extends javax.swing.JFrame {

    /**
     * Creates new form PrintRequestWindow
     */
    String method = "";
    public PrintRequestWindow() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        workOrderBox = new javax.swing.JCheckBox();
        receiptBox = new javax.swing.JCheckBox();
        workOrdernReceiptBox = new javax.swing.JCheckBox();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        titleLabel.setText("Select the print method");

        workOrderBox.setText("Work order");
        workOrderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrderBoxActionPerformed(evt);
            }
        });

        receiptBox.setText("Receipt");
        receiptBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptBoxActionPerformed(evt);
            }
        });

        workOrdernReceiptBox.setText("Work order & Receipt");
        workOrdernReceiptBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrdernReceiptBoxActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workOrdernReceiptBox)
                    .addComponent(receiptBox)
                    .addComponent(workOrderBox)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(saveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(workOrderBox)
                .addGap(18, 18, 18)
                .addComponent(receiptBox)
                .addGap(18, 18, 18)
                .addComponent(workOrdernReceiptBox)
                .addGap(35, 35, 35)
                .addComponent(saveBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workOrderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrderBoxActionPerformed
        // TODO add your handling code here:
        if(receiptBox.isSelected() || workOrdernReceiptBox.isSelected() && workOrderBox.isSelected()) {
            workOrderBox.setSelected(false);
            return;
        }
        method = EasyDelievery.PRINT_WORK_ORDER;
    }//GEN-LAST:event_workOrderBoxActionPerformed

    private void receiptBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptBoxActionPerformed
        // TODO add your handling code here:
        if(workOrderBox.isSelected() || workOrdernReceiptBox.isSelected() && receiptBox.isSelected()) {
            receiptBox.setSelected(false);
            return;
        }
        method = EasyDelievery.PRINT_RECEIPT;
    }//GEN-LAST:event_receiptBoxActionPerformed

    private void workOrdernReceiptBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrdernReceiptBoxActionPerformed
        // TODO add your handling code here:
        if(receiptBox.isSelected() || workOrderBox.isSelected() && workOrdernReceiptBox.isSelected()) {
            workOrdernReceiptBox.setSelected(false);
            return;
        }
        method = EasyDelievery.PRINT_BOTH;
    }//GEN-LAST:event_workOrdernReceiptBoxActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        File dbFile = new File(EasyDelievery.DB_FILE_NAME);
            if(!dbFile.exists()) {
                try {
                    dbFile.createNewFile();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane,  "Unable to create the configuration file, please try again", "File create failed", JOptionPane.WARNING_MESSAGE);
                    Logger.getLogger(ApplicationInit.class.getName()).log(Level.SEVERE, null, ex);
                    return;
                }
            }
            try {
                FileWriter fr = new FileWriter(EasyDelievery.DB_FILE_NAME, true);
                BufferedWriter br = new BufferedWriter(fr);
                br.append("\n");
                br.append(method);
                br.close();
                EasyDelievery.CURRENT_METHOD = method;
            } catch (IOException ex) {
                Logger.getLogger(ApplicationInit.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane,  "Unable to create the configuration file, please try again", "File create failed", JOptionPane.WARNING_MESSAGE);
                return;
            }
            EasyDelievery.window = new MainWindow();
            EasyDelievery.window.Start();
            this.dispose();
            
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintRequestWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox receiptBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JCheckBox workOrderBox;
    private javax.swing.JCheckBox workOrdernReceiptBox;
    // End of variables declaration//GEN-END:variables
}
