/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easy.delievery;

import java.awt.Window;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Server
 */
public class PrintRequestWindow extends javax.swing.JFrame {

    /**
     * Creates new form PrintRequestWindow
     */
    String method = "";
    boolean isEditing;
    public PrintRequestWindow(boolean isEditing) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.isEditing = isEditing;
        if(!EasyDelievery.CURRENT_TYPES.isEmpty()) {
            if(EasyDelievery.CURRENT_TYPES.equals("all")) {
                showStockItems.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        workOrderBox = new javax.swing.JCheckBox();
        receiptBox = new javax.swing.JCheckBox();
        workOrdernReceiptBox = new javax.swing.JCheckBox();
        saveBtn = new javax.swing.JButton();
        noneBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        showStockItems = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        titleLabel.setText("Select the print method");

        workOrderBox.setText("Work order");
        workOrderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrderBoxActionPerformed(evt);
            }
        });

        receiptBox.setText("Receipt");
        receiptBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptBoxActionPerformed(evt);
            }
        });

        workOrdernReceiptBox.setText("Work order & Receipt");
        workOrdernReceiptBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrdernReceiptBoxActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        noneBox.setText("None");
        noneBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noneBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noneBox)
                            .addComponent(workOrdernReceiptBox)
                            .addComponent(receiptBox)
                            .addComponent(workOrderBox)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(saveBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(workOrderBox)
                .addGap(18, 18, 18)
                .addComponent(receiptBox)
                .addGap(18, 18, 18)
                .addComponent(workOrdernReceiptBox)
                .addGap(18, 18, 18)
                .addComponent(noneBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Print method", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Settings for items");

        showStockItems.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        showStockItems.setText("Show Items with no stock");
        showStockItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStockItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showStockItems)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(showStockItems)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Items Settings", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void workOrderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrderBoxActionPerformed
        // TODO add your handling code here:
        if(receiptBox.isSelected() || noneBox.isSelected() || workOrdernReceiptBox.isSelected() && workOrderBox.isSelected()) {
            workOrderBox.setSelected(false);
            return;
        }
        method = EasyDelievery.PRINT_WORK_ORDER;
    }//GEN-LAST:event_workOrderBoxActionPerformed

    private void receiptBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptBoxActionPerformed
        // TODO add your handling code here:
        if(workOrderBox.isSelected() || noneBox.isSelected() || workOrdernReceiptBox.isSelected() && receiptBox.isSelected()) {
            receiptBox.setSelected(false);
            return;
        }
        method = EasyDelievery.PRINT_RECEIPT;
    }//GEN-LAST:event_receiptBoxActionPerformed

    private void workOrdernReceiptBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrdernReceiptBoxActionPerformed
        // TODO add your handling code here:
        if(receiptBox.isSelected() || noneBox.isSelected() || workOrderBox.isSelected() && workOrdernReceiptBox.isSelected()) {
            workOrdernReceiptBox.setSelected(false);
            return;
        }
        method = EasyDelievery.PRINT_BOTH;
    }//GEN-LAST:event_workOrdernReceiptBoxActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        File dbFile = new File(EasyDelievery.DB_FILE_NAME);
            if(!dbFile.exists()) {
                try {
                    dbFile.createNewFile();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane,  "Unable to create the configuration file, please try again", "File create failed", JOptionPane.WARNING_MESSAGE);
                    Logger.getLogger(ApplicationInit.class.getName()).log(Level.SEVERE, null, ex);
                    return;
                }
            }
            try {
                FileWriter fr = new FileWriter(EasyDelievery.DB_FILE_NAME, !isEditing);
                BufferedWriter br = new BufferedWriter(fr);
                if(isEditing) {
                    br.write(EasyDelievery.CURRENT_DB);
                    br.write("\n");
                }
                br.write(method);
                br.close();
                EasyDelievery.CURRENT_METHOD = method;
            } catch (IOException ex) {
                Logger.getLogger(ApplicationInit.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane,  "Unable to create the configuration file, please try again", "File create failed", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(!isEditing) {
                EasyDelievery.window = new MainWindow();
                EasyDelievery.window.Start();
            }
            this.dispose();
            
    }//GEN-LAST:event_saveBtnActionPerformed

    private void noneBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noneBoxActionPerformed
        // TODO add your handling code here:
        if(receiptBox.isSelected() || workOrderBox.isSelected() || workOrdernReceiptBox.isSelected()) {
            return;
        }
        method = EasyDelievery.NONE;
    }//GEN-LAST:event_noneBoxActionPerformed

    private void showStockItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStockItemsActionPerformed
        String method = "";
        if(showStockItems.isSelected()) {
            method = "all";
        } else {
            method = "stock";
        }
            File dbFile = new File(EasyDelievery.DB_FILE_NAME);
            if(!dbFile.exists()) {
                try {
                    dbFile.createNewFile();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane,  "Unable to create the configuration file, please try again", "File create failed", JOptionPane.WARNING_MESSAGE);
                    Logger.getLogger(ApplicationInit.class.getName()).log(Level.SEVERE, null, ex);
                    return;
                }
            }
            try {
                FileWriter fr = new FileWriter(EasyDelievery.DB_FILE_NAME, !isEditing);
                BufferedWriter br = new BufferedWriter(fr);
                if(isEditing) {
                    br.write(EasyDelievery.CURRENT_DB);
                    br.write("\n");
                }
                br.write(EasyDelievery.CURRENT_METHOD);
                br.write("\n");
                br.write(method);
                EasyDelievery.CURRENT_TYPES = method;
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(ApplicationInit.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane,  "Unable to create the configuration file, please try again", "File create failed", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(isEditing) {
                EasyDelievery.window.Reload();
            }
    }//GEN-LAST:event_showStockItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintRequestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox noneBox;
    private javax.swing.JCheckBox receiptBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JCheckBox showStockItems;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JCheckBox workOrderBox;
    private javax.swing.JCheckBox workOrdernReceiptBox;
    // End of variables declaration//GEN-END:variables
}
